//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMP_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderMaster
    {
        public int OrderID { get; set; }
        public string Ordercode { get; set; }
        public Nullable<System.DateTime> DateM { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public Nullable<decimal> Taxamount { get; set; }
        public Nullable<int> CourseID { get; set; }
        public Nullable<byte> Mode { get; set; }
        public Nullable<int> EntityID { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Phonenumber { get; set; }
        public string Address { get; set; }
        public string Remarks { get; set; }
        public string Status { get; set; }
        public string ResponseCode { get; set; }
        public string ResponseMessage { get; set; }
        public Nullable<int> TransactionID { get; set; }
    }
}
